name: Enterprise CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.filter.outputs.api }}
      ui: ${{ steps.filter.outputs.ui }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            api:
              - 'api/**'
              - 'infra/**'
            ui:
              - 'ui/**'
              - 'infra/**'

  build-and-deploy-api:
    needs: detect-changes
    if: needs.detect-changes.outputs.api == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Zip API
        run: |
          cd api
          zip -r ../api.zip .
      - name: Deploy API to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-hussain-api-unique-992'
          package: 'api.zip'

  build-and-deploy-ui:
    needs: detect-changes
    if: needs.detect-changes.outputs.ui == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Zip UI
        run: |
          cd ui
          zip -r ../ui.zip .
      - name: Deploy UI to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-hussain-ui-unique-992'
          package: 'ui.zip'